apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ms
spec:
  
  selector:
   matchLabels:
     app: back-ms
  template:
    metadata:
      labels:
        app: back-ms
    spec:
      containers:
        - name: back-ms
          image: sepulveda/back_cakephp:v1
          ports:
            - containerPort: 8100
          env:
            - name: host
              value: mysql
            - name: database
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_PORT
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD