apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ms
spec:
  selector:
   matchLabels:
     app: back-ms
  template:
    metadata:
      labels:
        app: back-ms
    spec:
      containers:
        - name: back-ms
          image: sepulveda/back_cakephp:v1
          ports:
            - containerPort: 8100
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
