apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-db
spec:
  type: NodePort
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 33069
      targetPort: 33069
