apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdmysql-pv
  labels:
    name: mysql-pv
spec:
  capacity:
    storage: 100M
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-cluster
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bdmysql-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeName: mysql-pv
